version: 2.1

# See https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0

jobs:
  build:
    docker:
    - image: python:3.8
    steps:
    - checkout
    - restore_cache:
        keys:
          # when lock files change, use increasingly general patterns to restore cache
          - &cache_key
            python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-{{ checksum "requirements.txt" }}
          - python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-
          - python-packages-v1-{{ .Branch }}-
          - python-packages-v1-
    - &build
      run:
        name: Build
        command: |
          python3.8 -m venv venv/
          venv/bin/pip install --progress-bar off --upgrade -r requirements.txt
    - run:
        name: PyTest
        command: venv/bin/pytest --black --flake8 --ignore=jetstream_config_parser/tests/integration/
    - run:
        name: isort
        command: venv/bin/isort --check jetstream_config_parser
    - run:
        name: Mypy
        command: venv/bin/mypy jetstream_config_parser
    - save_cache:
        paths:
        - venv/
        key: *cache_key
  integration:
    docker:
    - image: python:3.8
    steps:
    - checkout
    - *build
    - integration_test:
      run:
        name: PyTest Integration Test
        command: |
          venv/bin/pytest --black --flake8 --integration jetstream_config_parser/tests/integration/
  deploy:
    docker:
      - image: python:3.8-buster
    steps:
      - checkout
      - run:
          name: Install deployment tools
          command: |
            pip install --upgrade setuptools wheel twine
      - run:
          name: Create the distribution files
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Upload to PyPI
          command: |
            # Relies on the TWINE_USERNAME and TWINE_PASSWORD environment variables configured at:
            #   https://circleci.com/gh/mozilla/jetstream-config-parser/edit#env-vars
            # For more on twine, see:
            #   https://twine.readthedocs.io/en/latest/
            twine upload dist/*

workflows:
  version: 2.1
  build:
    jobs:
      - build
  tagged-deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /[0-9]{4}.[0-9]{1,2}.[0-9]+/  # Calver: YYYY.M.MINOR
            branches:
              # Ignore all branches; this workflow should only run for tags.
              ignore: /.*/
